scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['http://calc1-svc', 'http://calc2-svc', 'http://storage-svc']
        labels:
          application: 'Calculator'